name: CI Runner
on: [push, pull_request]

concurrency:
  group: ci-${{github.actor}}-${{github.head_ref || github.run_number}}-${{github.ref}}-runner
  cancel-in-progress: true

# In parallel, build and run the host tests, and check the formatting. If both succeed, build and upload the release
# artifacts. Also build the LaTeX manual.
jobs:
  build-test:
    name: Build Host Tests
    uses: ./.github/workflows/build.yml
    with:
      preset: host

  code-style:
    name: Code Style
    uses: ./.github/workflows/code_style.yml

  build-release:
    name: Release Build
    needs: [build-test, code-style]
    uses: ./.github/workflows/build.yml
    with:
      preset: release

  manual:
    name: Build LaTeX Manual
    uses: ./.github/workflows/latex.yml
    with:
      directory: manual
      name: manual

  deploy-pages:
    name: Deploy GitHub Pages
    needs: manual
    permissions:
      id-token: write
      pages: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: manual
          path: site
      - uses: actions/upload-pages-artifact@v3
        with:
          path: site
      - uses: actions/deploy-pages@v4
